### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by nisrulz** [nisrulz/AndroidAutomations#43]
Setup:

- [ ] [Detekt](https://github.com/detekt/detekt)
- [ ] [Danger](https://github.com/danger/danger)
- [ ] [Ktlint](https://github.com/pinterest/ktlint)
- [ ] [Git Hooks](https://github.com/harliedharma/android-git-hooks)
- [ ] Github Actions with Fastlane
- [ ] [Version Catalog](https://blog.stylingandroid.com/gradle-version-catalogs/)
- [ ] [Validate Gradle Wrapper Github Action](https://github.com/Drjacky/MVVMTemplate/blob/master/.github/workflows/gradlew-validation.yml)
- [ ] [Pre Merge Checks Github Action](https://github.com/Drjacky/MVVMTemplate/blob/master/.github/workflows/pre-merge.yml)
- [ ] Android Github Action - Runs assembleDebug task.
- [ ] View Binding
- [ ] Convert code to Kotlin
- [ ] [.gitattributes](https://www.droidcon.com/2022/03/10/removing-noise-from-your-github-language-stats/)
- [ ] [version-catalog-update-plugin](https://github.com/littlerobots/version-catalog-update-plugin)
- [ ] lib module, with Github Actions setup to publish lib
- [ ] [Chucker](https://github.com/ChuckerTeam/chucker)
- [ ] [Gradle Doctor](https://runningcode.github.io/gradle-doctor/)
- [ ] [Leak Canary](https://square.github.io/leakcanary/)
